# This is a basic workflow to help you get started with Actions

# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Build
# This workflow will install Python dependencies, run tests and lint with a single version of Python

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
        # python setup.py build_ext --inplace
        python setup.py install
    - name: Lint with flake8
      run: |
        pip install flake8
        pip install flake8-import-order
        pip install flake8-blind-except
        pip install flake8-builtins
        pip install flake8-docstrings
        pip install flake8-rst-docstrings
        pip install flake8-logging-format 
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --application-import-names='<temperatures>' --ignore=D210,D100,D104,D401,D202,E202,E201,I201 --show-source --enable-extension=G --max-line-length=140 --max-complexity=7 --count
    - name: Test with pytest
      run: |
        pytest . -vs
