# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Fetch LFS files
      run : |
        sudo apt-get install git-lfs -y
        git lfs install
        git lfs fetch --all
        git lfs pull
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        export DEVELOPER=true
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config="./setup.cfg"
    - name: Test with pytest
      run: |
        pytest . -v -m "not long"
